var currentLevel = null;
var levels = {
    "1-1": {
        saveCode: "20;air-180:leaf:air-19:leaf-2:air-18:oak_wood:air-18:sand:oak_wood:air-18:grass-2:dried_mud:air-16:monster:grass:dirt:dried_mud:mud:water-11:air-3:grass-2:dirt-3:mud-2:water-12:mud:grass:dirt-5:mud-6:water-3:mud-5:dirt-10:dried_mud:mud-5:dirt-47:air-400:0;400:",
        pixelInventory: {},
        name: "A Pixel World",
        description: "Welcome to <b>Pixel Simulator 2</b>! <b>Pixel Simulator 2</b> is a puzzle/sandbox game where you can simulate interactions of different <b>pixels</b>. <b>Pixels</b> are placed in a square grid, which you can see on the left side of your screen. Each square of the grid we will call <b>Tiles</b>. Even though they are called <b>Pixels</b>, a <b>pixel</b> is not actually just 1 solid color, and may be made of many. In levels, the goal is to destroy all the <b>monsters</b> (red <b>pixels</b>). Various methods to do this will be shown in later levels. Don't worry about it now.<br><br>If you get stuck on a level, don't worry, you can skip it. Some levels you may find a lot harder than the previous levels. Levels with a letter instead of a number are <b>bonus levels</b>. These levels take taught mechanics and use them to their full extent, in often challenging to figure out ways. These levels are meant to challenge you.<br><br>The sidebar is on the right side of your screen. The top is the level description, which you are reading right now. Underneath it, is the <b>Pixel Picker</b>. Here, you can see the pixels you have to beat a level. Click on a pixel in the <b>Pixel Picker</b> to select it. Underneath the <b>Pixel Picker</b> is the pixel description, which gives you a description of the pixel, what it does, and various statistics about the pixel, like its <b>density</b>, <b>blast resistance</b>, and how <b>flammable</b> it is. At the very bottom are the control and navigation buttons. These buttons are pretty self-explanatory.<br><br><b>Controls:</b><br><b>Left Click</b>: Place Pixels.<br><b>Right Click</b>: Remove Pixels.<br><b>Middle Click</b>: Pick Pixel. (Selects the pixel underneath the cursor.)<br><b>Scroll</b> or <b>Up/Down Arrows</b>: Change Click Size.<br><b>Ctrl+Scroll</b>: Zoom In/Out<br><b>W-A-S-D</b>: Move Camera.<br><br>Click <b>Run</b> to continue.",
    },
    "1-2": {
        saveCode: "20;air-149:leaf-3:air-5:leaf-3:air-8:leaf-5:air-3:leaf-4:air-8:leaf-2:oak_wood:leaf-2:air-3:leaf-4:air-10:oak_wood:air-7:oak_wood:air-12:oak_wood:air-6:oak_wood:air:grass:air-10:oak_wood:air-6:oak_wood:air:grass-2:air:monster:air:grass-3:monster:air-2:oak_wood:air-6:grass-2:dirt:grass-5:dirt-2:grass-9:monster:grass:dirt-101:air-400:1;100:300:",
        pixelInventory: {
            dirt: 1,
            sand: 1,
            water: 1,
        },
        name: "Gravitational Forces",
        description: "Most <b>pixels</b> in Pixel Simulator 2 follow gravity. Dirt and Grass fall downwards unless there are at least 4 pixels touching them. Sand falls and likes to make hills. Water will always try to reach the lowest elevation.<br><br><b>Placing Pixels</b>: The shaded square is where the pixel will be placed. In sandbox mode, you can place and remove <b>pixels</b> anywhere and also while the simulation is running. In levels, you have a limited amount of <b>pixels</b>, and may not place or remove once the simulation has started. Clicking <b>Reset</b> will reset the simulation back to before it started. In levels, you can only place and remove on the shaded <b>Placeable</b> tiles.<br><br><b>Destroying Monsters</b><br><br>If a <b>pixel</b> falls onto a <b>monster</b>, both the falling <b>pixel</b> and the monster get disintegrated. Using the given <b>pixels</b>, place them on the shaded Placeable tiles and destroy all the <b>monsters</b> to win!",
    },
    "1-A": {
        saveCode: "20;air-43:grass-4:air-16:grass-4:air-17:grass-2:air-101:monster-2:air-17:leaf-3:air-16:leaf-5:air-15:leaf-2:oak_wood:leaf-2:air-17:oak_wood:air-5:leaf-3:air-3:leaf:air-6:oak_wood:air-5:monster:leaf-4:air:leaf-2:air-2:monster:air-3:oak_wood:air-5:leaf-2:oak_wood:leaf-2:air:leaf-2:grass-3:air-3:oak_wood:air-7:oak_wood:air-4:oak_wood:dirt-2:grass-2:monster:grass-2:air-7:oak_wood:air-4:oak_wood:dirt-6:grass-2:monster:grass-6:monster:grass:monster:grass:dirt-21:air-400:0;47:1:9:1:4:1:4:1:45:1:3:1:4:1:8:1:45:1:222:",
        pixelInventory: {
            dirt: 1,
            grass: 1,
            sand: 5,
            water: 2,
        },
        name: "Hide and Seek",
        description: "Look! There are <b>monsters</b> hiding everywhere! It seems like each <b>monster</b> has a restriction for which <b>pixels</b> can destroy them. You only have a limited number of <b>pixels</b>, so use them wisely.",
    },
    "1-3": {
        saveCode: "20;air-4:water:air-41:water:air-4:water:air-43:leaf-3:air-16:leaf-5:monster:air-10:leaf-2:air:leaf-7:air-9:leaf-3:air:leaf-3:oak_wood:leaf-3:air-6:leaf-2:air:leaf:oak_wood:leaf:air-2:leaf-2:oak_wood-2:air-8:leaf:oak_wood:air:oak_wood:air-6:oak_wood-2:air-4:leaf-2:air-4:oak_wood-2:air-6:oak_wood-2:air-3:leaf-5:air-3:oak_wood:air-6:oak_wood-3:air-2:leaf-5:air-3:oak_wood:air-7:oak_wood-2:air-4:oak_wood:air-5:oak_wood:air-7:oak_wood-2:grass:air-3:oak_wood:air-5:oak_wood:air-7:grass:dirt-2:air:monster:air:oak_wood:air-2:monster:air-2:oak_wood:air-6:grass-2:dirt-2:grass-8:air:oak_wood:air-2:monster:grass-4:dirt-10:grass-6:dirt-47:air-400:0;50:1:20:4:10:1:8:1:8:2:55:1:239:",
        pixelInventory: {
            sand: 1,
            oak_wood: 2,
            leaf: 6,
            sapling: 1,
        },
        name: "Oak Forest",
        description: "Some <b>pixels</b> don't follow gravity, like oak wood and leaves. Leaves also will decay into saplings if it touches less than 2 other leaves and no wood. The water scattered around this forest could be useful if you could make it fall onto the <b>monsters</b>.",
    },
    "1-4": {
        saveCode: "20;air-144:grass-3:air-12:grass:air-4:grass-7:air-5:grass-4:air-5:grass-2:dirt-2:grass-2:air-5:grass:dirt-3:air-6:grass:dirt-2:grass:air-6:grass-2:dirt-2:air-6:grass:dirt-2:grass:air-7:grass:dirt-2:air-6:grass:dirt-2:grass:air-7:grass:dirt-2:air-6:grass:dirt-2:grass-2:air-4:monster-2:grass:dirt-2:air-5:grass-2:dirt-3:grass:monster-2:air:monster-2:dirt-4:air-4:grass-2:dirt-4:grass-2:monster-2:air:monster:dirt-4:grass-3:air:grass:dirt-6:grass-3:dirt-8:grass:monster:grass:dirt-18:monster:dirt-36:air-400:0;85:1:1:1:2:1:29:1:15:1:1:1:14:1:6:1:239:",
        pixelInventory: {
            sand: 1,
            water: 3,
        },
        name: "Mud Landslide",
        description: "Oh no! There are tons of <b>monsters</b> and you only have 4 <b>pixels</b>! Don't you just hate when you are given an impossible level? Wait, that dirt doesn't look very stable though... maybe you could turn it into mud...",
    },
    "1-5": {
        saveCode: "20;air-39:water:air-5:leaf-3:oak_wood-2:dirt:sand:air-7:leaf:air-4:leaf-2:oak_wood:leaf:air:dirt:air:oak_wood:dirt:air-5:leaf-2:air-5:oak_wood:air:leaf-2:air-3:dirt:air-5:leaf:oak_wood:air-4:oak_wood:air:oak_wood:air-5:sand:oak_wood:air-5:oak_wood:grass:air-2:oak_wood-5:air:oak_wood:air:oak_wood-6:air-2:oak_wood:grass-4:oak_wood:air-10:oak_wood:grass-4:dirt-4:grass:air-10:grass-2:dirt-6:grass-2:air-11:grass-2:dirt-4:grass-2:air-13:grass:dirt-4:grass:air-14:grass:dirt-4:grass:air-14:grass-2:dirt-3:grass:air-15:grass:dirt-2:grass-2:air-15:grass:dirt-2:grass:air-16:mud:dirt-2:grass:monster:mud:water-14:mud:dirt-4:mud-5:water-6:mud-5:dirt-8:mud-8:dried_mud:dirt-24:air-400:0;13:7:13:6:14:6:14:5:17:1:1:1:302:",
        pixelInventory: {
            dirt: 1,
            sand: 2,
            leaf: 6,
            sapling: 2,
        },
        name: "Broken Bridge",
        description: "A tree collapsed and broke the bridge! How will we get over now? Wait, a <b>monster</b> is hiding under the bridge. But how do we destroy it from up here?",
    },
    "2-1": {
        saveCode: "20;air-205:oak_wood-2:air-17:oak_wood-4:air-15:oak_wood-6:air-6:oak_wood-2:air-5:oak_wood-2:air-4:oak_wood-2:air-4:oak_wood-4:air-5:oak_wood:air:monster:air-2:oak_wood:air-4:oak_wood-2:air-2:oak_wood-2:air-4:oak_wood:monster-2:air:monster:oak_wood:air-5:oak_wood:air:monster:oak_wood:air:grass-11:air-4:oak_wood:monster:air:oak_wood:grass-2:dirt-9:grass-9:dirt-42:air-400:0;144:1:255:",
        pixelInventory: {
            lava: 1,
        },
        name: "Volcanic Destruction",
        description: "It seems like the <b>monsters</b> are adapting here as we approach <b>The Volcano</b>. I have no idea what <b>The Volcano</b> is, but I'm sure we'll learn more later. These <b>monsters<b> figured out how to build houses to protect themselves! How can we break in? I wonder if Oak Wood is flammable...",
    },
    "2-2": {
        saveCode: "20;air-194:basalt:stone:obsidian-2:basalt:air-4:obsidian-2:basalt-2:obsidian:air-5:obsidian-2:oak_wood-3:basalt:obsidian-2:air:basalt-2:oak_wood-3:obsidian:basalt:air-2:basalt:obsidian:basalt:oak_wood-2:air:oak_wood-2:obsidian:basalt:obsidian-2:oak_wood-2:air:oak_wood-2:basalt:obsidian-3:basalt:oak_wood-2:air-3:oak_wood-2:air:basalt:oak_wood-2:air-3:oak_wood-2:basalt:air-2:basalt:obsidian:oak_wood:air-2:monster:oak_wood:air-2:obsidian:basalt:oak_wood:air-2:monster:oak_wood:obsidian:basalt:air-3:basalt:oak_wood:monster-3:oak_wood:air:grass-2:dirt:grass:monster-2:air:oak_wood:basalt:air-4:obsidian:oak_wood:air:grass:dirt:grass-2:dirt-5:grass-3:obsidian:air-3:grass-5:dirt-11:grass-5:dirt-47:air-400:1;100:300:",
        pixelInventory: {
            water: 1,
            lava: 1,
        },
        name: "Rocky Shells",
        description: "Water can cool Lava into Stone, Basalt, and Obsidian! The more Lava surrounding the Lava when it cools, the stronger the rock it cools into! Obsidian is the strongest rock, followed by Basalt, then Stone. These rocks are immune to fire, but not to Lava. How can you get in to their houses now?",
    },
    "2-3": {
        saveCode: "20;air-242:oak_wood-3:air-3:obsidian:basalt:obsidian:air-8:basalt:oak_wood-7:air:obsidian:water:basalt:lava-8:basalt:air:oak_wood:air-3:oak_wood:air-2:basalt:water:obsidian-2:lava-8:air:oak_wood:monster:air:monster:oak_wood:air-2:obsidian:water:obsidian:lava-9:grass-3:monster-2:oak_wood:air-2:obsidian:water:obsidian:lava-9:dirt-2:grass-3:oak_wood:air-2:basalt:water:obsidian:lava-9:dirt-4:grass-4:obsidian:water:basalt:obsidian:lava-8:dirt-8:basalt:water:obsidian-2:lava-8:air-400:0;80:10:10:11:9:12:16:5:16:11:10:10:11:9:180:",
        pixelInventory: {
            sand: 3,
            oak_wood: 5,
            leaf: 12,
            ash: 2,
        },
        name: "Burnt Ash",
        description: "The monsters built a wall to protect them from the Lava! Fire is less dense than air, and will move upwards. There is a 25% chance for pixels to turn into Ash after being burnt. Ash turns into Silt once touching Water. How do we get the fire over the wall?",
    },
    "2-4": {
        saveCode: "20;air-66:obsidian-2:basalt-2:obsidian:basalt:air-13:basalt:air-6:obsidian:air-11:obsidian:air-8:obsidian:air-10:basalt:air-3:monster:air-2:monster:air:basalt:air-6:grass-2:air-2:obsidian:oak_wood:air:monster-2:air:monster-2:oak_wood:obsidian:air-3:grass-3:dirt:grass-2:basalt:obsidian:basalt:oak_wood-6:obsidian:basalt-2:grass-3:dirt-5:obsidian:basalt:obsidian-2:basalt:oak_wood-2:obsidian:basalt-2:obsidian-3:dirt-6:obsidian:basalt:air-11:basalt:obsidian:dirt-5:basalt:air-13:obsidian:dirt-5:obsidian:air-13:basalt:dirt-5:obsidian:air-13:basalt:dirt-5:basalt:air-13:obsidian:dirt-5:obsidian:basalt:air-11:basalt:obsidian:dirt-6:obsidian-2:air-9:obsidian-2:dirt-8:basalt:obsidian:basalt:obsidian:air-4:basalt:obsidian:basalt:dirt-12:obsidian:basalt-2:obsidian:basalt:obsidian:dirt-27:air-348:fire-4:air-48:0;307:5:14:7:67:",
        pixelInventory: {
            sand: 3,
            water: 5,
            ash: 2,
        },
        name: "Steam Engines",
        description: "Looks like the monsters built their house on a bridge! How can we destroy them from under the bridge?",
    },
    "2-5": {
        saveCode: "20;air-119:lava:air-12:basalt:water:basalt:air-2:basalt-3:air-11:basalt:obsidian-8:air-11:obsidian-9:air-10:basalt:obsidian-9:air-10:basalt:obsidian-3:monster:air-2:obsidian-3:air-9:basalt-2:obsidian-3:monster-3:obsidian-3:air-6:stone:gunpowder:basalt-3:gunpowder-3:monster-3:obsidian-3:air-5:stone-2:gunpowder:basalt-3:obsidian:gunpowder:obsidian-7:grass-2:air-2:stone:basalt-3:gunpowder-2:basalt:gunpowder-2:obsidian-7:dirt:grass-4:dirt-5:gunpowder:obsidian-9:dirt-80:air-400:0;32:7:13:7:341:",
        pixelInventory: {
            dirt: 1,
            sand: 3,
            water: 1,
            oak_wood: 2,
            basalt: 1,
            gunpowder: 1,
        },
        name: "Fiery Explosions",
        description: "An obsidian box? How are we supposted to break in now? Wait, is that a trail of gunpowder I see?",
    },
    "2-6": {
        saveCode: "40;air-834:oak_wood-3:air-36:oak_wood-2:air:oak_wood-2:air-36:oak_wood:air:oak_wood:air-89:sand-6:air-16:sand-5:oak_wood-2:air:oak_wood-2:sand-15:air-12:sand-9:oak_wood:water:oak_wood:sand-17:air-9:sand-11:oak_wood:water:oak_wood:sand-18:monster:sand:monster-2:sand-15:oak_wood:water:oak_wood:sand-37:oak_wood:water:oak_wood:sand-37:oak_wood:water:oak_wood:sand-37:oak_wood:water:oak_wood:sand-37:oak_wood:water:oak_wood:sand-37:stone:water:stone:sand-2:stone-3:sand-10:stone-2:sand-16:stone-5:water:stone-11:sand-2:stone-9:sand-10:stone-7:water:stone-39:water:stone-3:water:stone-32:water-8:stone-28:water-12:stone-27:water-13:air-1600:0;879:1:39:1:38:2:35:1:1:3:600:",
        pixelInventory: {
            dirt: 2,
            sand: 2,
            oak_wood: 4,
            steam: 1,
            stone: 2,
        },
        name: "Oh Well",
        description: "Make sure to bring water when you visit the desert! I brought plently, in this well. Wait, how will I even get the water out? Nevermind, it seems like there are <b>monsters</b> hiding in that ditch over there. You have some water, right? No? Oh well, I guess we'll never be able to destroy the monsters...",
    },
    "3-1": {
        saveCode: "20;air-64:sand:air-39:water:air-38:oak_wood:air:oak_wood:air-37:oak_wood:air:oak_wood:air-44:oak_wood-2:air-8:lava:air-8:oak_wood-4:air-7:sand:air-7:oak_wood-6:air-6:sand-4:air-5:oak_wood:air-2:oak_wood:air-2:sand-11:air-3:oak_wood:air:monster:sand-88:air-400:0;144:1:18:1:20:1:215:",
        pixelInventory: {
            snow: 1,
        },
        name: "Frozen Desert",
        description: "Snow in a desert? Crazy! Anyways, how do we stop the water from blocking the lava? Maybe we could freeze it with snow...",
    },
    "3-2": {
        saveCode: "20;ice-3:snow-10:ice-3:snow-4:ice:snow-6:ice-5:snow-2:ice-3:snow-7:ice-6:snow-5:ice-3:snow-4:ice-4:snow-11:ice-2:snow-11:ice-4:snow-6:stone-6:snow-3:ice-3:snow-6:ice-2:stone-7:snow-9:ice-3:snow:air-4:stone-3:air-4:stone-3:snow-3:ice:snow-2:air-11:stone-6:snow-3:air-13:stone-7:air-17:stone-3:water:air-18:stone-6:air-15:stone-12:air-6:monster:air:snow-7:stone-12:air:snow-15:stone-5:snow-2:ice-2:snow-8:ice-2:snow-9:ice-3:snow-4:ice-3:snow-5:ice-3:snow-3:ice-3:snow-3:ice-2:snow-6:ice-3:snow-16:ice-3:air-400:0;147:4:249:",
        pixelInventory: {
            sand: 4,
            frost_fire: 4,
        },
        name: "Chilly Cave",
        description: "Brrrr! It's freezing in here! Oh no! The cave is going to collapse and block the water! We only have sand to block it! What do we do?",
    },
    "3-3": {
        saveCode: "20;air-64:snow:air-18:snow:leaf:snow:air-7:snow:air-9:leaf-3:air-6:snow:leaf:snow:air-7:snow-2:spruce_wood:snow-2:air-4:monster:leaf-3:air-7:leaf-2:spruce_wood:leaf-2:air-3:snow-3:spruce_wood:snow-3:air-6:leaf:spruce_wood:leaf:air-4:leaf-3:spruce_wood:leaf-3:air-4:snow-3:spruce_wood:snow-3:air-3:leaf-2:spruce_wood:leaf-2:monster:air-4:leaf-3:spruce_wood:leaf-3:air:snow-4:spruce_wood:snow-4:air-4:leaf-2:spruce_wood:leaf-2:air-2:leaf-4:spruce_wood:leaf-4:air-2:monster:air-3:spruce_wood:air-5:leaf-3:spruce_wood:leaf-3:air-2:monster:ice-2:monster:air:spruce_wood:air-8:spruce_wood:air-5:ice:snow-8:air:monster:ice-3:spruce_wood:air:snow-5:dirt-7:snow-4:ice-2:snow-3:dirt-14:snow-4:dirt-66:air-400:1;1:8:3:5:4:8:3:5:4:16:4:339:",
        pixelInventory: {
            dirt: 3,
            sand: 7,
            water: 1,
        },
        name: "Snowy Forest",
        description: "Look at those giant spruce trees! Oh, watch your step. You don't want to trip on the ice boulders over here!",
    },
    "4-1": {
        saveCode: "20;obsidian-4:monster-2:air-14:obsidian:monster:obsidian-2:air-2:obsidian-13:air:obsidian:air:obsidian-2:air-2:obsidian-13:air:obsidian:air:obsidian-2:air-2:obsidian-13:air:obsidian:air:obsidian-2:air-2:obsidian-13:air:obsidian:air:obsidian-2:air-2:obsidian-9:monster:air-3:monster:obsidian:air-19:obsidian:monster:air-3:monster:air-11:monster:air-2:obsidian:air-19:obsidian:air:obsidian-2:air-2:obsidian-9:monster:air-3:monster:obsidian:air:obsidian-2:air-2:obsidian-15:air:obsidian-2:air-2:obsidian-15:air:obsidian-2:air-2:obsidian:air-12:obsidian-2:air:obsidian-2:air-2:obsidian:air:monster:air-10:obsidian-2:air:obsidian-2:air-2:obsidian:air-12:obsidian-2:air:obsidian-2:air-2:obsidian-15:air:obsidian-2:air-2:obsidian-15:air:obsidian-2:air-15:obsidian-2:air:obsidian-2:air-15:obsidian-21:air-400:0;19:1:97:1:25:1:11:1:3:1:37:1:79:1:67:1:15:1:2:2:34:",
        pixelInventory: {
            piston_left: 4,
            piston_right: 1,
            piston_up: 4,
            piston_down: 2,
        },
        name: "Movement Madness",
        description: "Whoa, these are some fancy pixels! The push themselves and are not affected by gravity!",
    },
    "4-2": {
        saveCode: "20;obsidian-42:monster:air-15:obsidian-4:air-15:monster:obsidian-10:monster:obsidian-19:monster:obsidian-13:air:monster:air-2:obsidian-2:monster:obsidian-5:air:monster:air:monster:obsidian-4:air-4:obsidian-2:air-4:obsidian-2:air-4:obsidian-4:air-4:obsidian-2:air-4:obsidian-2:air-4:obsidian-4:air-4:obsidian-2:air-4:obsidian-2:air-4:obsidian-4:air-4:obsidian-2:air-4:obsidian-2:air-4:obsidian-4:air-10:obsidian-2:air-4:obsidian-4:air-10:obsidian-2:air-4:obsidian-4:air-4:obsidian-2:air-4:obsidian-2:air-4:obsidian-4:air-4:obsidian-2:air-4:obsidian-2:air-4:obsidian-4:air-4:obsidian-2:air-4:obsidian-2:air-4:obsidian-6:air-2:obsidian-2:air-4:obsidian-2:air-4:obsidian-3:air-4:obsidian-3:air-4:obsidian-2:air-4:obsidian-42:air-400:0;52:2:8:1:9:1:235:2:18:2:4:2:5:2:5:2:4:2:44:",
        pixelInventory: {
            piston_left: 3,
            piston_right: 3,
            piston_up: 4,
            piston_down: 1,
        },
        name: "Clever Pushing",
        description: "Hmm, how do we get to the monsters? Maybe if we use pistons to push other pistons...",
    },
    "4-3": {
        saveCode: "20;obsidian-42:monster-6:obsidian-2:monster-6:air-2:obsidian-4:monster-6:obsidian-2:monster-6:air-2:obsidian-4:monster-6:obsidian-2:monster-6:air-2:obsidian-4:monster-6:obsidian-2:monster-6:air-2:obsidian-4:monster-6:obsidian-2:monster-4:obsidian-2:air-2:obsidian-4:monster-6:obsidian-2:monster-4:obsidian-2:air-2:obsidian-4:monster-6:obsidian-2:monster-4:obsidian-2:air-2:obsidian-4:monster-6:obsidian-2:monster-4:obsidian-2:air-2:obsidian-4:monster-6:obsidian-14:monster-6:obsidian-14:air-16:obsidian-4:air-16:obsidian-4:air-16:obsidian-4:air-14:obsidian:air:obsidian-4:air-16:obsidian-4:air-16:obsidian-42:air-400:0;176:2:18:2:75:4:16:4:16:3:17:4:63:",
        pixelInventory: {
            piston_left: 1,
            piston_up: 1,
            piston_down: 1,
            cloner_left: 1,
            cloner_up: 2,
        },
        name: "Infinite Clones",
        description: "The room is flooding with monsters! Wait, is that a cloner? Cloners clone the pixel behind them and push it in front of them! We can use this to destroy all the monsters.",
    },
    "4-A": {
        saveCode: "20;obsidian-42:air-16:obsidian-4:air-16:obsidian-4:air-16:obsidian-4:air-16:obsidian-4:air-16:obsidian-4:air-16:obsidian-4:air-16:obsidian-4:air-16:obsidian-18:air-2:obsidian-18:air-2:obsidian-4:monster-12:obsidian-2:air-2:obsidian-4:monster-12:obsidian-2:air-2:obsidian-4:monster-12:obsidian-2:air-2:obsidian-4:monster-12:obsidian-2:air-2:obsidian-4:air-16:obsidian-4:air-16:obsidian-42:air-400:0;42:4:16:4:16:4:16:4:16:4:16:4:16:4:16:4:214:",
        pixelInventory: {
            cloner_left: 1,
            cloner_right: 4,
            cloner_up: 1,
            cloner_down: 2,
        },
        name: "Around the Corner",
        description: "These monsters thinking they're so sneaky, hiding behind that wall. You have tons of cloners, surely you can find a way to get around the corner.",
    },
    "4-4": {
        saveCode: "20;obsidian-42:air-16:obsidian-4:air-16:obsidian-4:air-6:monster:air-9:obsidian-9:air:monster:obsidian-2:air-2:obsidian-14:air-2:obsidian-2:air-2:obsidian-9:air-14:monster-2:obsidian-4:air-7:obsidian-2:air-2:obsidian-2:air:monster:air:obsidian-4:air-7:obsidian-2:air-2:obsidian-2:air:monster:air:obsidian-4:air-11:obsidian-2:air:monster:air:obsidian-4:air-11:obsidian-2:air-3:obsidian-4:air-11:obsidian-2:air-3:obsidian-4:air:obsidian-2:air-2:obsidian-8:air-3:obsidian-4:air-4:monster:obsidian-8:air:monster:air:obsidian-4:air-11:obsidian-2:air:monster:air:obsidian-4:air-11:obsidian-2:air:monster:air:obsidian-4:air-11:obsidian-2:air:monster:air:obsidian-42:air-400:0;42:5:6:5:24:5:6:5:30:1:13:2:18:2:44:1:21:3:3:1:13:3:3:1:19:1:35:1:9:2:18:2:8:1:47:",
        pixelInventory: {
            piston_left: 1,
            piston_right: 1,
            cloner_up: 1,
            rotator_clockwise: 7,
            rotator_counter_clockwise: 2,
        },
        name: "Spinny Rotator",
        description: "Rotators will rotate pistons and cloners they touch by 90 degrees. Seems like you need to rotate some pistons to move in other directions to navigate this maze and destroy the monsters. Good luck!",
    },
    "4-5": {
        saveCode: "20;obsidian-42:air-6:obsidian:air-2:obsidian:air-6:obsidian-4:air-16:obsidian-5:air:obsidian-5:air-2:obsidian-5:air:obsidian-5:air-3:obsidian:air-3:monster:air-4:obsidian:air-3:obsidian-4:air:monster:air:obsidian:air:monster:air-6:obsidian:air:monster:air:obsidian-4:air:monster-2:obsidian:air-3:monster:air-4:monster:air:monster-2:obsidian-4:air:monster:air:obsidian:air:monster:air:monster:air-2:monster:air-3:monster:air:obsidian-4:air-3:obsidian:air:monster:air:monster:air-4:obsidian:air:monster:air:obsidian-4:air:monster:air-8:monster:air:obsidian:air:monster:air:obsidian-4:air:monster:air-3:monster:air:monster:air-4:obsidian:air-3:obsidian-4:air:monster:air:obsidian:air-3:monster:air-2:monster:air:obsidian:air:monster:air:obsidian-4:air:monster:air:obsidian:air:monster:air-4:monster:air-5:obsidian-4:air-3:obsidian:air:monster:air:monster:air-6:monster:air:obsidian-4:air:monster:air:obsidian:air-6:monster:air:obsidian:air:monster:air:obsidian-4:air-3:obsidian:air:monster:air-6:obsidian:air-3:obsidian-4:air-3:obsidian:air-8:obsidian:air-3:obsidian-42:air-400:0;62:1:4:5:4:2:5:1:5:2:5:1:11:1:2:1:20:1:189:1:1:1:10:1:1:1:4:1:1:1:1:1:1:1:1:1:1:1:2:1:1:1:42:",
        pixelInventory: {
            piston_left: 2,
            piston_right: 1,
            cloner_left: 1,
            cloner_right: 1,
            cloner_down: 3,
            rotator_clockwise: 3,
            rotator_counter_clockwise: 1,
            alternator: 6,
        },
        name: "Clocked Pistons",
        description: "Alternators are like rotators, except they rotate by 180 degrees. Useful if you need a quick turn. This formation of monsters is unusual, almost as if they are lining up for a reason. Well, I guess we'll find out later, for now, use these alternators to destroy the monsters!",
    },
    "4-B": {
        saveCode: "20;obsidian-42:air-7:obsidian-2:air-3:monster:air:obsidian:air:obsidian-4:air:monster-3:air-3:obsidian-2:air-2:monster-2:air-3:obsidian-4:monster:air:obsidian:monster:obsidian:monster:air-4:monster:air-3:obsidian:air:obsidian-4:monster:air:obsidian:air:obsidian:air-2:obsidian-2:monster:air:obsidian-2:air:obsidian:air:obsidian-4:air-7:obsidian-2:air-2:obsidian-2:monster:obsidian:air:obsidian-4:air-7:obsidian-2:air-2:obsidian-2:air:obsidian:air:obsidian-13:monster:air:obsidian-2:air:obsidian:air:obsidian-13:monster:air:obsidian-2:air:obsidian-6:air-7:monster:air-3:monster-2:air-3:obsidian-4:air-9:monster:air-4:monster:air:obsidian-4:air-2:obsidian-3:air:obsidian-3:air-2:obsidian-2:air-3:obsidian-4:air-2:obsidian-3:monster:obsidian-3:air-2:obsidian-2:monster:air-2:obsidian-4:air-2:obsidian:air-2:monster-2:air:obsidian:air-2:obsidian-2:air:monster:air:obsidian-4:monster:air:obsidian-2:air-2:monster:obsidian-2:monster:air:obsidian-2:monster-2:air:obsidian-4:air-4:monster-2:air-5:obsidian-2:air:monster:air:obsidian-4:air-8:monster:air-2:obsidian-2:air-3:obsidian-8:air:obsidian:air:obsidian-31:air-400:0;51:1:3:1:1:1:4:1:5:1:7:1:16:1:11:1:2:1:33:1:2:1:2:1:8:1:19:1:28:3:8:1:67:1:3:1:13:1:31:1:1:1:4:1:4:1:4:1:2:3:8:1:1:1:31:",
        pixelInventory: {
            piston_up: 1,
            cloner_left: 1,
            cloner_up: 2,
            cloner_down: 1,
            rotator_clockwise: 3,
            rotator_counter_clockwise: 7,
            alternator: 7,
        },
        name: "Rectangular Rooms",
        description: "Look at these hallways crowding with monsters! Those cloners will definitely be useful. But only 4? I guess you will have to find another way...",
    },
    "vault": {
        saveCode: "50;air-932:oak_wood:air-8:oak_wood:air-39:oak_wood:explosives:rotator_clockwise-8:explosives:oak_wood:air-39:rotator_clockwise:explosives:obsidian-6:explosives:rotator_clockwise:air-40:rotator_clockwise:obsidian:explosives:obsidian-4:explosives:obsidian:rotator_clockwise:air-40:rotator_clockwise:obsidian-2:explosives:obsidian-2:explosives:obsidian-2:rotator_clockwise:air-40:rotator_clockwise:obsidian-3:monster-2:obsidian-3:rotator_clockwise:air-40:rotator_clockwise:obsidian-3:monster-2:obsidian-3:rotator_clockwise:air-40:rotator_clockwise:obsidian-2:explosives:obsidian-2:explosives:obsidian-2:rotator_clockwise:air-40:rotator_clockwise:obsidian:explosives:obsidian-4:explosives:obsidian:rotator_clockwise:air-40:rotator_clockwise:explosives:obsidian-6:explosives:rotator_clockwise:air-39:oak_wood:explosives:rotator_clockwise-8:explosives:oak_wood:air-39:oak_wood:air-8:oak_wood:air-1008:air-2500:0;857:6:44:6:44:6:44:6:44:6:44:6:1387:",
        pixelInventory: {
            piston_up: 1,
            ignitor_left: 1,
            rotator_clockwise: 1,
            rotator_counter_clockwise: 1,
        },
        name: "Vault lol",
        description: "testing testing VAULT",
    },
    "vault2": {
        saveCode: "100;air-5138:deleter-29:air-66:deleter-5:cloner_right-29:deleter-5:air-61:deleter-5:cloner_right-29:deleter-5:air-61:deleter-5:cloner_right-29:deleter-5:air-61:deleter-5:cloner_right-29:deleter-5:air-61:deleter-5:cloner_right-29:deleter-5:air-60:deleter:cloner_up-7:deleter-4:cloner_up-2:deleter-4:cloner_up-5:deleter-4:cloner_up-2:deleter:cloner_up-2:deleter:cloner_down:cloner_right:cloner_down-5:deleter:air-59:deleter:cloner_up-5:cloner_right-26:deleter:cloner_down:cloner_right:cloner_down-5:deleter:air-59:deleter:cloner_up-5:deleter-27:cloner_down:deleter:cloner_down-5:deleter:air-59:deleter:cloner_up-5:cloner_left:cloner_up:deleter:obsidian-23:deleter:cloner_down:deleter:cloner_down-5:deleter:air-59:deleter:cloner_up-5:cloner_left:cloner_up:deleter:obsidian-23:deleter:cloner_down:deleter:cloner_down-5:deleter:air-59:deleter:cloner_up-5:deleter:cloner_up:deleter:obsidian-2:deleter-19:obsidian-2:deleter:cloner_down:deleter:cloner_down-5:deleter:air-59:deleter:cloner_up-5:cloner_left:cloner_up:deleter:obsidian-2:deleter:obsidian-17:deleter:obsidian-2:deleter:cloner_down:cloner_right:cloner_down-5:deleter:air-59:deleter:cloner_up-5:cloner_left:cloner_up:deleter:obsidian-2:deleter:obsidian-17:deleter:obsidian-2:deleter:cloner_down:cloner_right:cloner_down-5:deleter:air-59:deleter:cloner_up-5:deleter:cloner_up:deleter:obsidian-2:deleter:obsidian-17:deleter:obsidian-2:deleter:cloner_down:deleter:cloner_down-5:deleter:air-59:deleter:cloner_up-5:deleter:cloner_up:deleter:obsidian-2:deleter:obsidian-3:deleter-11:obsidian-3:deleter:obsidian-2:deleter:cloner_down:deleter:cloner_down-5:deleter:air-59:deleter:cloner_up-5:deleter:cloner_up:deleter:obsidian-2:deleter:obsidian-3:deleter:obsidian-9:deleter:obsidian-3:deleter:obsidian-2:deleter:cloner_down:deleter:cloner_down-5:deleter:air-59:deleter:cloner_up-5:deleter:cloner_up:deleter:obsidian-2:deleter:obsidian-3:deleter:obsidian-9:deleter:obsidian-3:deleter:obsidian-2:deleter:cloner_down:deleter:cloner_down-5:deleter:air-59:deleter:cloner_up-5:cloner_left:cloner_up:deleter:obsidian-2:deleter:obsidian-3:deleter:obsidian-2:air-5:obsidian-2:deleter:obsidian-3:deleter:obsidian-2:deleter:cloner_down:cloner_right:cloner_down-5:deleter:air-59:deleter:cloner_up-5:cloner_left:cloner_up:deleter:obsidian-2:deleter:obsidian-3:deleter:obsidian-2:air-2:monster:air-2:obsidian-2:deleter:obsidian-3:deleter:obsidian-2:deleter:cloner_down:cloner_right:cloner_down-5:deleter:air-59:deleter:cloner_up-5:cloner_left:cloner_up:deleter:obsidian-2:deleter:obsidian-3:deleter:obsidian-2:air:oak_wood-3:air:obsidian-2:deleter:obsidian-3:deleter:obsidian-2:deleter:cloner_down:cloner_right:cloner_down-5:deleter:air-59:deleter:cloner_up-5:cloner_left:cloner_up:deleter:obsidian-2:deleter:obsidian-3:deleter:obsidian-2:air-2:oak_wood:air-2:obsidian-2:deleter:obsidian-3:deleter:obsidian-2:deleter:cloner_down:cloner_right:cloner_down-5:deleter:air-59:deleter:cloner_up-5:deleter:cloner_up:deleter:obsidian-2:deleter:obsidian-3:deleter:obsidian-9:deleter:obsidian-3:deleter:obsidian-2:deleter:cloner_down:deleter:cloner_down-5:deleter:air-59:deleter:cloner_up-5:deleter:cloner_up:deleter:obsidian-2:deleter:obsidian-3:deleter:obsidian-9:deleter:obsidian-3:deleter:obsidian-2:deleter:cloner_down:deleter:cloner_down-5:deleter:air-59:deleter:cloner_up-5:deleter:cloner_up:deleter:obsidian-2:deleter:obsidian-3:deleter-11:obsidian-3:deleter:obsidian-2:deleter:cloner_down:deleter:cloner_down-5:deleter:air-59:deleter:cloner_up-5:deleter:cloner_up:deleter:obsidian-2:deleter:obsidian-17:deleter:obsidian-2:deleter:cloner_down:deleter:cloner_down-5:deleter:air-59:deleter:cloner_up-5:cloner_left:cloner_up:deleter:obsidian-2:deleter:obsidian-17:deleter:obsidian-2:deleter:cloner_down:cloner_right:cloner_down-5:deleter:air-59:deleter:cloner_up-5:cloner_left:cloner_up:deleter:obsidian-2:deleter:obsidian-17:deleter:obsidian-2:deleter:cloner_down:cloner_right:cloner_down-5:deleter:air-59:deleter:cloner_up-5:deleter:cloner_up:deleter:obsidian-2:deleter-19:obsidian-2:deleter:cloner_down:deleter:cloner_down-5:deleter:air-59:deleter:cloner_up-5:deleter:cloner_up:deleter:obsidian-23:deleter:cloner_down:cloner_right:cloner_down-5:deleter:air-59:deleter:cloner_up-5:deleter:cloner_up:deleter:obsidian-23:deleter:cloner_down:cloner_right:cloner_down-5:deleter:air-59:deleter:cloner_up-5:deleter:cloner_up:deleter-27:cloner_down-5:deleter:air-59:deleter:cloner_up-5:cloner_left:cloner_up:deleter:cloner_left-26:cloner_down-5:deleter:air-59:deleter:cloner_up-5:cloner_left:cloner_up:deleter:cloner_down-2:deleter:cloner_down-2:deleter-4:cloner_down-5:deleter-4:cloner_down-2:deleter-4:cloner_down-7:deleter:air-60:deleter-5:cloner_left-29:deleter-5:air-61:deleter-5:cloner_left-29:deleter-5:air-61:deleter-5:cloner_left-29:deleter-5:air-61:deleter-5:cloner_left-29:deleter-5:air-61:deleter-5:cloner_left-29:deleter-5:air-66:deleter-29:air-933:air-10000:1;4320:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:37:63:17:",
        pixelInventory: {
            all: 1000000,
            ignitor_launcher_left: -1000000,
            ignitor_launcher_right: -1000000,
            ignitor_launcher_up: -1000000,
            ignitor_launcher_down: -1000000,
            frost_ignitor_launcher_left: -1000000,
            frost_ignitor_launcher_right: -1000000,
            frost_ignitor_launcher_up: -1000000,
            frost_ignitor_launcher_down: -1000000,
        },
        name: "OP VAULT",
        description: "sp head confirmed??",
    },
    "vault3": {
        // saveCode: "100;air-4046:deleter-17:air-82:deleter:slider_horizontal-17:deleter:air-76:deleter-5:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:deleter-5:air-71:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-71:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-71:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-71:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-70:deleter:slider_horizontal-5:obsidian-2:cloner_up-15:obsidian-2:slider_horizontal-5:deleter:air-68:deleter:slider_vertical:cloner_up-5:obsidian-2:cloner_left-7:basalt:cloner_right-7:obsidian-2:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_up-5:cloner_left:cloner_up:obsidian-15:cloner_up:cloner_right:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_up-5:cloner_left:cloner_up:obsidian-15:cloner_up:cloner_right:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_up-5:cloner_left:cloner_up:obsidian-15:cloner_up:cloner_right:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_up-5:cloner_left:cloner_up:obsidian-15:cloner_up:cloner_right:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_up-5:cloner_left:cloner_up:obsidian-15:cloner_up:cloner_right:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_up-5:cloner_left:cloner_up:obsidian-15:cloner_up:cloner_right:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_up-5:cloner_left:cloner_up:obsidian-6:monster-3:obsidian-6:cloner_up:cloner_right:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:basalt-5:cloner_left:basalt:obsidian-6:monster-3:obsidian-6:basalt:cloner_right:basalt-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:cloner_left:cloner_down:obsidian-6:monster-3:obsidian-6:cloner_down:cloner_right:cloner_down-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:cloner_left:cloner_down:obsidian-15:cloner_down:cloner_right:cloner_down-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:cloner_left:cloner_down:obsidian-15:cloner_down:cloner_right-2:cloner_down-4:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:cloner_left:cloner_down:obsidian-15:cloner_down:cloner_right-2:cloner_down-4:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:cloner_left:cloner_down:obsidian-15:cloner_down:cloner_right:cloner_down-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:cloner_left:cloner_down:obsidian-15:cloner_down:cloner_right:cloner_down-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:cloner_left:cloner_down:obsidian-15:cloner_down:cloner_right:cloner_down-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:obsidian-2:cloner_left-7:basalt:cloner_right-7:obsidian-2:cloner_down-5:slider_vertical:deleter:air-68:deleter:slider_horizontal-5:obsidian-2:cloner_down-15:obsidian-2:slider_horizontal-5:deleter:air-70:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-71:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-71:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-71:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-71:deleter-5:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:deleter-5:air-76:deleter:slider_horizontal-17:deleter:air-82:deleter-17:air-2737:air-10000:1;2725:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:1919:",
        saveCode: "100;air-4046:deleter-17:air-82:deleter:slider_horizontal-17:deleter:air-76:deleter-5:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:deleter-5:air-71:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-71:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-71:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-71:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-70:deleter:slider_horizontal-5:obsidian-2:cloner_up-15:obsidian-2:slider_horizontal-5:deleter:air-68:deleter:slider_vertical:cloner_up-5:obsidian-2:cloner_left-7:basalt:cloner_right-7:obsidian-2:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_up-5:cloner_left:cloner_up:obsidian-2:basalt-11:obsidian-2:cloner_up:cloner_right:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_up-5:cloner_left:cloner_up:obsidian-2:cloner_up-11:obsidian-2:cloner_up:cloner_right:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_up-5:cloner_left:cloner_up:basalt:cloner_left:basalt-11:cloner_right:basalt:cloner_up:cloner_right:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_up-5:cloner_left:cloner_up:basalt:cloner_left:basalt:obsidian-9:basalt:cloner_right:basalt:cloner_up:cloner_right:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_up-5:cloner_left:cloner_up:basalt:cloner_left:basalt:obsidian-9:basalt:cloner_right:basalt:cloner_up:cloner_right:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_up-5:cloner_left:cloner_up:basalt:cloner_left:basalt:obsidian-9:basalt:cloner_right:basalt:cloner_up:cloner_right:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_up-5:cloner_left:cloner_up:basalt:cloner_left:basalt:obsidian-3:monster-3:obsidian-3:basalt:cloner_right:basalt:cloner_up:cloner_right:cloner_up-5:slider_vertical:deleter:air-67:deleter:slider_vertical:basalt-5:cloner_left:basalt-2:cloner_left:basalt:obsidian-3:monster-3:obsidian-3:basalt:cloner_right:basalt-2:cloner_right:basalt-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:cloner_left:cloner_down:basalt:cloner_left:basalt:obsidian-3:monster-3:obsidian-3:basalt:cloner_right:basalt:cloner_down:cloner_right:cloner_down-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:cloner_left:cloner_down:basalt:cloner_left:basalt:obsidian-9:basalt:cloner_right:basalt:cloner_down:cloner_right:cloner_down-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:cloner_left:cloner_down:basalt:cloner_left:basalt:obsidian-9:basalt:cloner_right:basalt:cloner_down:cloner_right:cloner_down-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:cloner_left:cloner_down:basalt:cloner_left:basalt:obsidian-9:basalt:cloner_right:basalt:cloner_down:cloner_right:cloner_down-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:cloner_left:cloner_down:basalt:cloner_left:basalt-11:cloner_right:basalt:cloner_down:cloner_right:cloner_down-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:cloner_left:cloner_down:obsidian-2:cloner_down-11:obsidian-2:cloner_down:cloner_right:cloner_down-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:cloner_left:cloner_down:obsidian-2:basalt-11:obsidian-2:cloner_down:cloner_right:cloner_down-5:slider_vertical:deleter:air-67:deleter:slider_vertical:cloner_down-5:obsidian-2:cloner_left-7:basalt:cloner_right-7:obsidian-2:cloner_down-5:slider_vertical:deleter:air-68:deleter:slider_horizontal-5:obsidian-2:cloner_down-15:obsidian-2:slider_horizontal-5:deleter:air-70:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-71:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-71:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-71:deleter:obsidian-4:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:obsidian-4:deleter:air-71:deleter-5:slider_vertical:cloner_left-8:basalt:cloner_right-8:slider_vertical:deleter-5:air-76:deleter:slider_horizontal-17:deleter:air-82:deleter-17:air-2737:air-10000:1;2725:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:44:56:1919:",
        pixelInventory: {
            all: 1000000,
            ignitor_launcher_left: -1000000,
            ignitor_launcher_right: -1000000,
            ignitor_launcher_up: -1000000,
            ignitor_launcher_down: -1000000,
            frost_ignitor_launcher_left: -1000000,
            frost_ignitor_launcher_right: -1000000,
            frost_ignitor_launcher_up: -1000000,
            frost_ignitor_launcher_down: -1000000,
        },
        name: "Vault 2",
        description: "even better",
    },
    "4rings": {
        saveCode: "100;air-3837:obsidian-3:slider_horizontal-27:obsidian-3:air-67:obsidian-3:swapper_vertical-27:obsidian-3:air-67:obsidian-3:slider_horizontal-27:obsidian-3:air-67:slider_vertical:swapper_horizontal:slider_vertical:obsidian-3:deleter-21:obsidian-3:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:obsidian-3:cloner_up-21:obsidian-3:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:obsidian-3:basalt-21:obsidian-3:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:obsidian-3:deleter-15:obsidian-3:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:obsidian-3:cloner_up-15:obsidian-3:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:obsidian-3:basalt-15:obsidian-3:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-3:deleter-9:obsidian-3:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-3:cloner_up-9:obsidian-3:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-3:basalt-9:obsidian-3:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-9:basalt:cloner_right:deleter:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-9:basalt:cloner_right:deleter:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-9:basalt:cloner_right:deleter:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-3:monster-3:obsidian-3:basalt:cloner_right:deleter:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-3:monster-3:obsidian-3:basalt:cloner_right:deleter:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-3:monster-3:obsidian-3:basalt:cloner_right:deleter:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-9:basalt:cloner_right:deleter:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-9:basalt:cloner_right:deleter:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-9:basalt:cloner_right:deleter:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-3:basalt-9:obsidian-3:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-3:cloner_down-9:obsidian-3:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:deleter:cloner_left:basalt:obsidian-3:deleter-9:obsidian-3:basalt:cloner_right:deleter:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:obsidian-3:basalt-15:obsidian-3:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:obsidian-3:cloner_down-15:obsidian-3:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:deleter:cloner_left:basalt:obsidian-3:deleter-15:obsidian-3:basalt:cloner_right:deleter:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:obsidian-3:basalt-21:obsidian-3:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:obsidian-3:cloner_down-21:obsidian-3:slider_vertical:swapper_horizontal:slider_vertical:air-67:slider_vertical:swapper_horizontal:slider_vertical:obsidian-3:deleter-21:obsidian-3:slider_vertical:swapper_horizontal:slider_vertical:air-67:obsidian-3:slider_horizontal-27:obsidian-3:air-67:obsidian-3:swapper_vertical-27:obsidian-3:air-67:obsidian-3:slider_horizontal-27:obsidian-3:air-2930:air-10000:1;3837:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:2930:",
        pixelInventory: {
            all: 1000000,
        },
        name: "4 Rings",
        description: "lots of buhsalt",
    },
    "impossible": {
        saveCode: "100;air-3837:obsidian:deleter-31:obsidian:air-67:deleter:obsidian:basalt-6:cloner_left:basalt-15:cloner_right:basalt-6:obsidian:deleter:air-67:deleter:basalt:obsidian:basalt-5:cloner_left:basalt-15:cloner_right:basalt-5:obsidian:basalt:deleter:air-67:deleter:basalt-2:obsidian:basalt-4:cloner_left:basalt-15:cloner_right:basalt-4:obsidian:basalt-2:deleter:air-67:deleter:basalt-3:obsidian:basalt-3:cloner_left:basalt-15:cloner_right:basalt-3:obsidian:basalt-3:deleter:air-67:deleter:basalt-4:obsidian:basalt-2:cloner_left:basalt-15:cloner_right:basalt-2:obsidian:basalt-4:deleter:air-67:deleter:basalt-5:obsidian:basalt:cloner_up-17:basalt:obsidian:basalt-5:deleter:air-67:deleter:basalt-6:obsidian:cloner_left:basalt-15:cloner_right:obsidian:basalt-6:deleter:air-67:deleter:cloner_up-5:cloner_left:cloner_up-5:cloner_right-13:cloner_down:cloner_right:cloner_down-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_up-4:cloner_right-13:basalt:cloner_right:basalt-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_up-7:cloner_right-10:basalt:cloner_right:basalt-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_up-4:cloner_right-13:basalt:cloner_right:basalt-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_up-5:cloner_left:cloner_up:cloner_right-6:cloner_down:cloner_right:cloner_down-2:basalt:cloner_right:basalt-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_up-5:cloner_left:cloner_up-7:cloner_down:cloner_right:cloner_down-2:basalt:cloner_right:basalt-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_up-5:cloner_left:cloner_up:cloner_right-6:cloner_down:cloner_right:cloner_down-2:basalt:cloner_right:basalt-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_up-5:cloner_left:cloner_up:obsidian-3:cloner_down:cloner_right:cloner_down-5:basalt:cloner_right:basalt-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_up-5:cloner_left:cloner_up:obsidian:monster:obsidian:cloner_down:cloner_right:cloner_down-5:basalt:cloner_right:basalt-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_up-5:cloner_left:cloner_up:obsidian-3:cloner_down:cloner_right:cloner_down-5:basalt:cloner_right:basalt-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_up-2:cloner_left:cloner_up:cloner_left-6:cloner_down:cloner_right:cloner_down-5:basalt:cloner_right:basalt-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_up-2:cloner_left:cloner_up:cloner_down-7:cloner_right:cloner_down-5:basalt:cloner_right:basalt-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_up-2:cloner_left:cloner_up:cloner_left-6:cloner_down:cloner_right:cloner_down-5:basalt:cloner_right:basalt-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_left-13:cloner_down-4:basalt:cloner_right:basalt-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_left-10:cloner_down-7:basalt:cloner_right:basalt-5:deleter:air-67:deleter:basalt-5:cloner_left:basalt:cloner_left-13:cloner_down-4:basalt:cloner_right:basalt-5:deleter:air-67:deleter:cloner_down-5:cloner_left:cloner_down:cloner_left-13:cloner_down-5:cloner_right:cloner_down-5:deleter:air-67:deleter:basalt-6:obsidian:cloner_left:basalt-15:cloner_right:obsidian:basalt-6:deleter:air-67:deleter:basalt-5:obsidian:basalt:cloner_down-17:basalt:obsidian:basalt-5:deleter:air-67:deleter:basalt-4:obsidian:basalt-2:cloner_left:basalt-15:cloner_right:basalt-2:obsidian:basalt-4:deleter:air-67:deleter:basalt-3:obsidian:basalt-3:cloner_left:basalt-15:cloner_right:basalt-3:obsidian:basalt-3:deleter:air-67:deleter:basalt-2:obsidian:basalt-4:cloner_left:basalt-15:cloner_right:basalt-4:obsidian:basalt-2:deleter:air-67:deleter:basalt:obsidian:basalt-5:cloner_left:basalt-15:cloner_right:basalt-5:obsidian:basalt:deleter:air-67:deleter:obsidian:basalt-6:cloner_left:basalt-15:cloner_right:basalt-6:obsidian:deleter:air-67:obsidian:deleter-31:obsidian:air-2930:air-10000:1;3837:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:67:33:2930:",
        pixelInventory: {
            all: 1000000,
        },
        name: "impossible",
        description: "impossible",
    },
    "reflector_vault": {
        saveCode: "100;air-4565:reflector_vertical:reflector_horizontal:air-97:reflector_vertical:obsidian-2:reflector_horizontal:air-95:reflector_vertical:obsidian:cloner_up:cloner_right:obsidian:reflector_horizontal:air-93:reflector_vertical:obsidian:cloner_up-2:cloner_right-2:obsidian:reflector_horizontal:air-91:reflector_vertical:obsidian:cloner_up-2:obsidian-2:cloner_right-2:obsidian:reflector_horizontal:air-89:reflector_vertical:obsidian:cloner_up-2:obsidian:deleter-2:obsidian:cloner_right-2:obsidian:reflector_horizontal:air-87:reflector_vertical:obsidian:cloner_up-2:obsidian:deleter-4:obsidian:cloner_right-2:obsidian:reflector_horizontal:air-85:reflector_vertical:obsidian:cloner_up-2:obsidian:deleter-2:rotator_clockwise-2:deleter-2:obsidian:cloner_right-2:obsidian:reflector_horizontal:air-83:reflector_vertical:obsidian:cloner_up-2:obsidian:deleter-2:rotator_clockwise:obsidian-2:rotator_clockwise:deleter-2:obsidian:cloner_right-2:obsidian:reflector_horizontal:air-81:reflector_vertical:obsidian:cloner_up-2:obsidian:deleter-2:rotator_clockwise:obsidian-4:rotator_clockwise:deleter-2:obsidian:cloner_right-2:obsidian:reflector_horizontal:air-79:reflector_vertical:obsidian:cloner_up-2:obsidian:deleter-2:rotator_clockwise:obsidian:cloner_up-4:obsidian:rotator_clockwise:deleter-2:obsidian:cloner_right-2:obsidian:reflector_horizontal:air-77:reflector_vertical:obsidian:cloner_up-2:obsidian:deleter-2:rotator_clockwise:obsidian-2:cloner_up-4:obsidian-2:rotator_clockwise:deleter-2:obsidian:cloner_right-2:obsidian:reflector_horizontal:air-75:reflector_vertical:obsidian:cloner_up-2:obsidian:deleter-2:rotator_clockwise:obsidian:cloner_left-2:obsidian-4:cloner_right-2:obsidian:rotator_clockwise:deleter-2:obsidian:cloner_right-2:obsidian:reflector_horizontal:air-73:reflector_vertical:obsidian:cloner_up-2:obsidian:deleter-2:rotator_clockwise:obsidian-2:cloner_left-2:obsidian:monster-2:obsidian:cloner_right-2:obsidian-2:rotator_clockwise:deleter-2:obsidian:cloner_right-2:obsidian:reflector_horizontal:air-72:reflector_horizontal:obsidian:cloner_left-2:obsidian:deleter-2:rotator_clockwise:obsidian-2:cloner_left-2:obsidian:monster-2:obsidian:cloner_right-2:obsidian-2:rotator_clockwise:deleter-2:obsidian:cloner_down-2:obsidian:reflector_vertical:air-73:reflector_horizontal:obsidian:cloner_left-2:obsidian:deleter-2:rotator_clockwise:obsidian:cloner_left-2:obsidian-4:cloner_right-2:obsidian:rotator_clockwise:deleter-2:obsidian:cloner_down-2:obsidian:reflector_vertical:air-75:reflector_horizontal:obsidian:cloner_left-2:obsidian:deleter-2:rotator_clockwise:obsidian-2:cloner_down-4:obsidian-2:rotator_clockwise:deleter-2:obsidian:cloner_down-2:obsidian:reflector_vertical:air-77:reflector_horizontal:obsidian:cloner_left-2:obsidian:deleter-2:rotator_clockwise:obsidian:cloner_down-4:obsidian:rotator_clockwise:deleter-2:obsidian:cloner_down-2:obsidian:reflector_vertical:air-79:reflector_horizontal:obsidian:cloner_left-2:obsidian:deleter-2:rotator_clockwise:obsidian-4:rotator_clockwise:deleter-2:obsidian:cloner_down-2:obsidian:reflector_vertical:air-81:reflector_horizontal:obsidian:cloner_left-2:obsidian:deleter-2:rotator_clockwise:obsidian-2:rotator_clockwise:deleter-2:obsidian:cloner_down-2:obsidian:reflector_vertical:air-83:reflector_horizontal:obsidian:cloner_left-2:obsidian:deleter-2:rotator_clockwise-2:deleter-2:obsidian:cloner_down-2:obsidian:reflector_vertical:air-85:reflector_horizontal:obsidian:cloner_left-2:obsidian:deleter-4:obsidian:cloner_down-2:obsidian:reflector_vertical:air-87:reflector_horizontal:obsidian:cloner_left-2:obsidian:deleter-2:obsidian:cloner_down-2:obsidian:reflector_vertical:air-89:reflector_horizontal:obsidian:cloner_left-2:obsidian-2:cloner_down-2:obsidian:reflector_vertical:air-91:reflector_horizontal:obsidian:cloner_left-2:cloner_down-2:obsidian:reflector_vertical:air-93:reflector_horizontal:obsidian:cloner_left:cloner_down:obsidian:reflector_vertical:air-95:reflector_horizontal:obsidian-2:reflector_vertical:air-97:reflector_horizontal:reflector_vertical:air-2733:air-10000:1;2935:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:35:65:",
        pixelInventory: {
            all: 1000000,
        },
        name: "noLASERSplz",
        description: "oof",
    },
    "nuked": {
        saveCode: "100;air-4763:deleter-15:air-85:deleter:air-13:deleter:air-85:deleter:air-13:deleter:air-85:deleter:air-13:deleter:air-85:deleter:air-5:rotator_clockwise:cloner_left:cloner_up:air-5:deleter:air-85:deleter:air-5:rotator_clockwise:cloner_left:cloner_up:air-5:deleter:air-85:deleter:air-3:cloner_left-2:obsidian-3:rotator_counter_clockwise-2:air-3:deleter:air-85:deleter:air-3:cloner_down-2:obsidian:monster:obsidian:cloner_up-2:air-3:deleter:air-85:deleter:air-3:rotator_counter_clockwise-2:obsidian-3:cloner_right-2:air-3:deleter:air-85:deleter:air-5:cloner_down:cloner_right:rotator_clockwise:air-5:deleter:air-85:deleter:air-5:cloner_down:cloner_right:rotator_clockwise:air-5:deleter:air-85:deleter:air-13:deleter:air-85:deleter:air-13:deleter:air-85:deleter:air-13:deleter:air-85:deleter-15:air-3822:air-10000:1;3042:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:42:58:2200:",
        pixelInventory: {
            all: 1000000,
        },
        name: "nuked",
        description: "BUH",
    },
    "box": {
        saveCode: "20;air-9:obsidian:cloner_right:obsidian:ignitor_right:ignitor_laser_right:air-15:obsidian:cloner_right:obsidian:deleter:obsidian:air-15:obsidian:cloner_right:obsidian:deleter:obsidian:air-15:obsidian:cloner_right:obsidian:deleter:obsidian:air-15:obsidian:cloner_right:obsidian:deleter:obsidian:air-15:obsidian:cloner_right:obsidian:deleter:obsidian:air-15:obsidian:cloner_right:obsidian:deleter:obsidian-7:air-9:obsidian:cloner_right:obsidian:deleter-8:air-9:obsidian:cloner_right:obsidian-9:air-9:obsidian:deleter:cloner_up-9:air-9:obsidian-11:air-173:monster:air-6:air-400:0;16:4:16:4:16:4:16:4:320:",
        pixelInventory: {
            fire: 1,
            frost_fire: 1,
            cloner_left: 1,
            cloner_right: 1,
            cloner_up: 1,
            cloner_down: 1,
            piston_left: 1,
            piston_right: 1,
            piston_up: 1,
            piston_down: 1,
            rotator_clockwise: 1,
            rotator_counter_clockwise: 1,
            alternator: 1,
            deletor: 1,
            swapper_horizontal: 1,
            swapper_vertical: 1,
            reflector_horizontal: 1,
            reflector_vertical: 1,
            ignitor_left: 1,
            ignitor_right: 1,
            ignitor_up: 1,
            ignitor_down: 1,
            frost_ignitor_left: 1,
            frost_ignitor_right: 1,
            frost_ignitor_up: 1,
            frost_ignitor_down: 1,
        },
        name: "box",
        description: "idk",
    },
};